In [7]:
# data read

import pandas as pd

df=pd.read_csv("raw_data.csv")
print(df)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handle missing values

In [9]:
# missing values

df.isnull() # return empty values (True)
df.isnull().sum() # total no. of mussing values

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [10]:
df.dropna() # row drop which have no missing data value

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [22]:
df.dropna(axis=1) # cloumn drop with no null element

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [20]:
df.fillna(0) # all missing value ~ 0

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [28]:
# calulate average of all age

cleaned_data= df.copy()
age_mean=cleaned_data["age"].mean()

cleaned_data["age"]= cleaned_data["age"].fillna(age_mean)

print(cleaned_data)

# df["age"].fillna(age_mean)  # rplace empty with mean value

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [32]:
# forward filling data

df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [33]:
# backward filling

df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [34]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handle duplication

In [38]:
# searching for duplication

df["country"].duplicated() # return Ture if duplicated data was there

df[["country","gender"]].duplicated() # if both are correct ~ Ture

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [41]:
# removing duplication (de_duplication)

df.drop_duplicates()  # delete duplicates

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handle data_type & date_time

In [43]:
df.dtypes # type of every column

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [46]:
# converting data type

# converting age data type (float to int)

df2=df.copy() # make a copy of dataset

df2=df2.fillna(0) # replace empty with 0
df2["age"]=df2["age"].astype("int64").copy()  # actual conversion
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [48]:
# data_time data

date_str=pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

## Handle Strings

In [53]:
# lowercase

df["gender"].str.lower()

# uppercase

df["gender"].str.upper()

# capitalize
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [58]:
# split

df["name"].str.split("") # split the letters
df["name"].str.split() # split the words

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [61]:
# search contains

df["country"].str.contains("India", case=False) # True if present

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object